package com.tag.main;

import java.util.List;

import com.tag.analyzer.RestAPISpecAnalyzer;
import com.tag.common.TAGException;
import com.tag.restapi.spec.parser.SwaggerSpecParser;
import com.tag.restapi.spec.vo.RestAPIInfo;
import com.tag.restapi.writer.FreeMarkerGenerator;
import com.tag.restapi.writer.RestAPITestSuiteVO;

import io.swagger.models.Swagger;

public class RestAPITestManager {
	SwaggerSpecParser parser = new SwaggerSpecParser();
	RestAPISpecAnalyzer analyzer = new RestAPISpecAnalyzer();
	FreeMarkerGenerator generator = new FreeMarkerGenerator();
	
	/**
	 * First, parse OpenAPI Spcification file(generated by Swagger),
	 * @param specFilePath
	 * @return
	 * @throws TAGException
	 */
	public String analyzeAndGenerate(String specFilePath) throws TAGException {
		Swagger swaggerInfo = parser.parseSpecFile(specFilePath);
		List<RestAPIInfo> restAPIInfoList =parser.parse(swaggerInfo);
		int failCount = 0;
		int generatedCount =0;
		StringBuffer returnMsg = new StringBuffer();
		for(RestAPIInfo restAPIInfo : restAPIInfoList) {
			try {
				RestAPITestSuiteVO testSuite = analyzer.analyze(restAPIInfo);
				String generateFilePath = generator.generateRestAssured(testSuite);
				generatedCount++;
				returnMsg.append(generateFilePath);
				returnMsg.append(",");
			}catch(Exception oneOfAllEx) {
				
			}
			returnMsg.append(",");
		}
		
		if(failCount >0) {
			//TODO	뭐할까?
		}
		return returnMsg.toString();
	}
	
}
